//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICSVImport")]
public interface ICSVImport
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICSVImport/EchoTest", ReplyAction="http://tempuri.org/ICSVImport/EchoTestResponse")]
    void SaveCSV(object ListPersons);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICSVImport/EchoTest", ReplyAction="http://tempuri.org/ICSVImport/EchoTestResponse")]
    System.Threading.Tasks.Task SaveCSVAsync(object ListPersons);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICSVImportChannel : ICSVImport, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CSVImportClient : System.ServiceModel.ClientBase<ICSVImport>, ICSVImport
{
    
    public CSVImportClient()
    {
    }
    
    public CSVImportClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CSVImportClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CSVImportClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CSVImportClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void SaveCSV(object ListPersons)
    {
        base.Channel.SaveCSV(ListPersons);
    }
    
    public System.Threading.Tasks.Task SaveCSVAsync(object ListPersons)
    {
        return base.Channel.SaveCSVAsync(ListPersons);
    }
}
